#!/bin/bash
# Get the absolute path to the directory where this AppRun script is located
SELF_DIR="$(dirname "$(readlink -f "$0")")"

# Execute your main script, passing all arguments ($@)
# and ensuring the path is relative to the internal AppImage mount
exec "$SELF_DIR/run-proton" "$@"
